---
- hosts: "{{ hostgroup }}"
  user: test
  become: yes
  become_method: sudo
  vars_files:
    - conf/vars_ansistrano.yml
    - conf/vars_server_base.yml
    - conf/vars_prod_deploy.yml
  vars:
    exec_path: /home/deployer/www/current
    deploy_path: /home/deployer/www/current
    repo_path: git@github.com:veracross/barrick-devops-test.git
    passenger_app_root: /home/deployer/www/prod/current/public
    git_force: yes
    redis_requirepass: "hithere"
    redis_env_var: "REDIS_PW"
    ana_dest_apth: /home/deployer/www/prod/current
  tasks:
  - name: base package installation
    apt: 
      name: "{{ packages }}"
      state: latest
    tags: setup
  - name: create deploy user # will require additional keys for git 
    user:
      name: "{{ deploy_user_name }}"
      group: "{{ deploy_user_group }}"
      shell: "{{ deploy_user_shell }}"
      append: yes
      # add key
    tags: setup
  - include: inc/sudoer.yml  # creates sudoers.d entry
  - name: create deploy directorires
    file:
      path: "{{ deploy_path }}"
      state: directory
      mode: 0775
      group: "{{ web_user_name }}"
    tags: setup
  roles:
    - geerlingguy.passenger
    - geerlingguy.redis

  # todo
  # ansible vault for redis pw and keys
