---
- hosts: "{{ hostgroup }}"
  become: yes
  become_method: sudo
  vars_files:
    - conf/vars_ansistrano.yml
    - conf/vars_server_base.yml
    - conf/vars_prod_deploy.yml
  tasks:
  - name: install prerequisite base packages
    apt: 
      name: "{{ packages }}"
      state: latest
    tags: setup
  - name: create deploy user # will require additional keys for git 
    user:
      name: "{{ deploy_user_name }}"
      group: "{{ deploy_user_group }}"
      shell: "{{ deploy_user_shell }}"
      append: yes
    tags: setup
  - include: inc/sudoer.yml  # creates sudoers.d entry
  - name: create deploy directorires
    file:
      path: "{{ deploy_path }}"
      state: directory
      mode: 0775
      group: "{{ deploy_user_group }}"
    tags: setup
  roles:
    - geerlingguy.passenger
    - geerlingguy.redis

  # todo
  # ansible vault for redis pw and keys
