- name: set permissions
  file: 
    path: "{{ deploy_path }}"
    state: directory
    recurse: yes
    owner: deployer
    group: www-data
    mode: 0775
- name: run bundler
  bundler:
    state: present
    chdir: "{{ deploy_path }}"
  become: yes
  become_user: "{{ deploy_user_name }}"
- name: restart nginx
  service:
    name: nginx
    state: restarted
- name: restart redis
  service:
    name: redis-server
    state: restarted
