---
- hosts: nginx-server
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    deploy_user: test
    sudo_nopass_entry: "ALL=(ALL:ALL) NOPASSWD: ALL"
  tasks:
    - name: update specific configuration files
      template:
        src: templates/sudoers.j2
        dest: "/etc/sudoers.d/{{ deploy_user }}"
        validate: "visudo -cf %s"
        owner: root
        group: root
        mode: 0440
      tags: setup

 # test    ALL=(ALL:ALL) NOPASSWD: ALL

